[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
